apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
spec:
  storageClassName: managed-nfs-storage # match defined storageclass name
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
